// create employee
export const CREATE_EMPLOYEE_REQUEST = "CREATE_EMPLOYEE_REQUEST";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAILURE = "CREATE_EMPLOYEE_FAILURE";

//get employee list

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILURE = "GET_EMPLOYEE_FAILURE";

//delete employee
export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE";

//get employee Details

export const GET_EMPLOYEE_DETAILS_REQUEST = "GET_EMPLOYEE_DETAILS_REQUEST";
export const GET_EMPLOYEE_DETAILS_SUCCESS = "GET_EMPLOYEE_DETAILS_SUCCESS";
export const GET_EMPLOYEE_DETAILS_FAILURE = "GET_EMPLOYEE_DETAILS_FAILURE";


//UPDATE employee Details

export const UPDATE_EMPLOYEE_DETAILS_REQUEST = "UPDATE_EMPLOYEE_DETAILS_REQUEST";
export const UPDATE_EMPLOYEE_DETAILS_SUCCESS = "UPDATE_EMPLOYEE_DETAILS_SUCCESS";
export const UPDATE_EMPLOYEE_DETAILS_FAILURE = "UPDATE_EMPLOYEE_DETAILS_FAILURE";